version: '3.7'

services:
  redis:
    image: redis:7.0.15
    container_name: redis
    ports:
      - "6379:6379"
    privileged: true

  web:
    build: .
    container_name: chess-trainer-backend
    depends_on:
      - redis
    ports:
      - "8000:8000"
    environment:
      JWT_SECRET: "secret"
      MONGO_URI: "mongodb+srv://sadavar:99jack@chesstrainer.d0yivsi.mongodb.net/?retryWrites=true&w=majority"
      CELERY_BROKER_URL: "redis://redis:6379/0"
      CELERY_RESULT_BACKEND: "redis://redis:6379/0"
    privileged: true
